version: '3.2'
services:
  db:
    image: rogersdk/mysql-rest-with-spring-boot-udemy
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context:  .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_springboot_udemy
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  rest-with-springboot-udemy:
    image: rogersdk/rest-with-spring-boot-udemy
    restart: always
    build: ./rest-with-springboot-udemy
    working_dir: /rest-with-springboot-udemy
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./rest-with-springboot-udemy:/rest-with-springboot-udemy
      - ~/.m2/root/.m2
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
    udemy-network:
        driver: bridge